allowBuilds:
  "@prisma/client": true
  "@prisma/engines": true
  agent-browser: true
  esbuild: true
  prisma: true
  unrs-resolver: true

onlyBuiltDependencies:
  - "@prisma/client"
  - "@prisma/engines"
  - agent-browser
  - esbuild
  - prisma
  - unrs-resolver
